(function(){
function addPremium(){
 if(!document.getElementById('history')){const s=document.createElement('section');s.id='history';s.className='page';s.innerHTML=`<div class="page-head"><div><div class="eyebrow">RECORDS</div><h1>Invoice History</h1><p class="muted">Saved invoices only. Open any bill to continue editing with the full billing editor.</p></div><button class="btn secondary" onclick="renderInvoiceHistory()">Refresh</button></div><div class="history-toolbar"><input id="historySearch" placeholder="Search invoice, customer or number" oninput="renderInvoiceHistory()"><select id="historyFilter" onchange="renderInvoiceHistory()"><option value="all">All</option><option value="pending">Pending</option><option value="paid">Paid</option></select></div><div id="invoiceHistoryList"></div>`;document.querySelector('.app').appendChild(s);}
 if(!document.getElementById('ai')){const s=document.createElement('section');s.id='ai';s.className='page';s.innerHTML=`<div class="page-head"><div><div class="eyebrow">INTELLIGENCE</div><h1>AI Copilot</h1><p class="muted">Local-first business intelligence that can recommend and actually apply safe changes inside SZ Billing.</p></div><div class="ai-orb">✦</div></div><div class="card"><label>Tell Copilot what you want</label><div class="row"><input id="aiCommand" placeholder="e.g. optimize my app, find overdue bills, repair invoice data"></div><div class="actions"><button class="btn" onclick="aiRunCommand()">Run Command</button><button class="btn secondary" onclick="aiApplyAllSafe()">Apply All Safe</button></div></div><div id="aiResult"></div><div class="card ai-actions"><button class="btn" onclick="aiAnalyze()">Run AI Check</button><button class="btn secondary" onclick="aiAutoRepair()">Safe Auto-Repair</button><button class="btn secondary" onclick="aiOptimizeTheme()">Optimize Design</button><button class="btn accent" onclick="aiScanAndQueue()">Scan Pending Reminders</button></div><div class="card" style="margin-top:12px"><div class="section-title">Automatic Reminder Engine</div><p class="muted small">Pending invoices can be detected and queued for follow-up without changing your existing invoice records.</p><div id="reminderQueue"></div></div>`;document.querySelector('.app').appendChild(s);}
}
window.renderInvoiceHistory=function(){const el=document.getElementById('invoiceHistoryList');if(!el)return;const q=(document.getElementById('historySearch')?.value||'').toLowerCase();const f=document.getElementById('historyFilter')?.value||'all';let a=(db.invoices||[]).slice().reverse().filter(i=>{const p=Number(i.pending||0)>0;return(f==='all'||(f==='pending'?p:!p))&&(!q||`${i.no} ${i.customer} ${i.date}`.toLowerCase().includes(q));});el.innerHTML=a.length?a.map(i=>`<div class="history-row"><div><div class="history-no">${esc(i.no||'Invoice')}</div><div class="muted small">${esc(i.customer||'Walk-in')} • ${esc(i.date||'')}</div></div><div class="history-money">${money(i.total||0)}<div class="small ${Number(i.pending||0)>0?'pending-text':'paid-text'}">${Number(i.pending||0)>0?money(i.pending)+' pending':'Paid'}</div></div><div class="actions"><button class="btn" onclick="openSavedBilling('invoice','${i.id}')">Edit</button><button class="btn secondary" onclick="viewSaved('invoice','${i.id}')">View</button><button class="btn accent" onclick="printSaved('invoice','${i.id}')">PDF</button>${Number(i.pending||0)>0?`<button class="btn ok" onclick="markSavedInvoicePaid('${i.id}')">Full Paid</button>`:''}</div></div>`).join(''):'<div class="empty">No invoice history found.</div>';};
const oldOpen=window.openPage;window.openPage=function(id){oldOpen(id);if(id==='history')renderInvoiceHistory();if(id==='ai'){aiInit();aiAnalyze();}};
document.addEventListener('DOMContentLoaded',()=>{addPremium();setTimeout(()=>{try{aiInit();aiAnalyze()}catch(e){console.warn(e)}},250);});
})();
