(function(){
'use strict';
/* SZ Billing V35 — consolidated mobile/desktop UX, navigation, billing and AI */
const css=`
/* V35 app-like responsive shell */
:root{--v35-gap:10px}
body{overflow-x:hidden}
#billing{max-width:780px!important;margin:0 auto!important}
#billing .page-head{position:sticky;top:0;z-index:20;padding:9px 0;background:rgba(248,250,252,.94);backdrop-filter:blur(12px);margin-bottom:8px}
.billing-v35{width:100%;display:block}
.billing-v35-card{background:#fff;border:1px solid #e6eaf0;border-radius:18px;box-shadow:0 6px 22px rgba(16,24,40,.055);overflow:hidden;margin-bottom:9px}
.billing-v35-head{padding:14px 15px;background:linear-gradient(135deg,#0b2552,#165dff);color:#fff}
.billing-v35-head h2{margin:3px 0;font-size:20px}.billing-v35-head p{margin:0;font-size:11px;opacity:.8}
.billing-v35-body{padding:10px}
.v35-section{padding:10px;border:1px solid #edf0f4;border-radius:15px;background:#fbfcfe;margin-bottom:8px}
.v35-section:last-child{margin-bottom:0}.v35-section h3{font-size:13px;margin:0 0 8px;font-weight:900}
.v35-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.v35-grid.three{grid-template-columns:repeat(3,1fr)}
.v35-grid>div{min-width:0}.v35-section input,.v35-section select,.v35-section textarea{min-height:40px!important;border-radius:11px!important;padding:8px 10px!important;font-size:13px}.v35-section textarea{min-height:54px!important}
.v35-items{background:#fff;border:1px solid #e4e8ee;border-radius:13px;overflow:hidden}.v35-item{display:grid;grid-template-columns:1fr auto;gap:8px;padding:9px 10px;border-bottom:1px solid #edf0f3}.v35-item:last-child{border-bottom:0}.v35-item b{font-size:13px}.v35-meta{font-size:10px;color:#667085;margin-top:2px}.v35-item-actions{display:flex;gap:5px;align-items:center}.v35-item-actions .btn{padding:6px 8px!important;font-size:11px!important;min-height:30px!important}
.v35-add{width:100%;min-height:42px;border:1px dashed #91b5f4;background:#f4f8ff;color:#155eef;border-radius:12px;margin-top:7px;font-weight:900}
.v35-totals{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.v35-total{background:#fff;border:1px solid #e6eaf0;border-radius:12px;padding:8px}.v35-total small{display:block;color:#667085;font-size:9px;font-weight:800}.v35-total b{font-size:13px}.v35-total.grand{background:#eef4ff;border-color:#cfe0ff}.v35-total.pending{background:#fff7ed;border-color:#fed7aa}
.v35-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.v35-actions .btn{width:100%;min-height:40px!important;padding:8px!important;border-radius:11px!important;font-size:12px!important}
.v35-sticky{position:sticky;bottom:0;z-index:30;background:rgba(248,250,252,.95);backdrop-filter:blur(12px);padding:7px 0;border-top:1px solid #e5e7eb}
.v35-note{text-align:center;font-size:10px;color:#667085;padding:5px}
/* A4 theme cards */
.design-option{cursor:pointer;transition:.18s transform,.18s box-shadow}.design-option:active{transform:scale(.98)}
.design-thumb{height:120px!important;background:#e9edf3!important;position:relative!important;overflow:hidden!important}.design-thumb:before{content:"";position:absolute;width:67px;height:94px;left:50%;top:13px;transform:translateX(-50%);background:#fff;border:1px solid #d7dde7;box-shadow:0 6px 14px rgba(15,23,42,.15);border-radius:2px}.design-thumb:after{content:"A4";position:absolute;left:50%;top:53px;transform:translateX(-50%);font-weight:950;font-size:12px;color:#165dff}.design-option.active{outline:2px solid #155eef;box-shadow:0 0 0 3px rgba(21,94,239,.1)}
.theme-preview-sheet{background:#dfe5ed!important;border-radius:16px!important;padding:12px!important;overflow:auto!important;display:flex!important;justify-content:center!important}.a4-stage{background:transparent!important;padding:0!important;display:flex!important;justify-content:center!important}.doc.a4-paper{width:210mm!important;min-height:297mm!important;max-width:none!important;background:#fff!important;box-shadow:0 15px 38px rgba(15,23,42,.22)!important;flex:none!important}
/* mobile item picker */
.sz-item-picker{max-height:82vh;display:flex;flex-direction:column}.sz-item-search{min-height:45px!important;border-radius:13px!important;margin:8px 0!important}.sz-item-list{overflow:auto;display:flex;flex-direction:column;gap:7px}.sz-pick{display:flex;width:100%;align-items:center;justify-content:space-between;text-align:left;padding:12px;border:1px solid #e1e6ed;border-radius:14px;background:#fff}.sz-pick small{display:block;color:#667085;font-size:11px;margin-top:2px}.sz-pick:active{transform:scale(.99)}
/* app-like pages on desktop and phone: no desktop billing canvas */
@media(min-width:781px){#billing{max-width:820px!important}.v35-section{padding:9px}.billing-v35-body{padding:10px}.billing-v35-card{border-radius:20px}}
@media(max-width:600px){#billing{max-width:100%!important}.v35-grid,.v35-grid.three{grid-template-columns:1fr 1fr}.v35-grid .full{grid-column:1/-1}.v35-totals{grid-template-columns:1fr 1fr}.v35-total.grand{grid-column:1/-1}.v35-actions{grid-template-columns:1fr 1fr}.v35-actions .wide{grid-column:1/-1}.billing-v35-head{padding:12px}.billing-v35-body{padding:7px}.v35-section{padding:8px}}
`;
const st=document.createElement('style');st.id='sz-v35-style';st.textContent=css;document.head.appendChild(st);
function E(s){return typeof esc==='function'?esc(s):String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function ensure(){db.settings=db.settings||{};db.settings.docTheme=db.settings.docTheme||'modern';db.settings.pendingPostTheme=db.settings.pendingPostTheme||'professional';db.settings.reminderDays=Math.max(1,Number(db.settings.reminderDays||3));}
function label(t){return ({modern:'Modern Blue',classic:'Classic Light',emerald:'Emerald Pro',midnight:'Midnight'}[t]||t)}
window.previewDocTheme=function(t){ensure();const obj={id:'preview',no:'INV-0001',date:new Date().toISOString().slice(0,10),due:new Date().toISOString().slice(0,10),customerId:'',customer:'Sample Customer',paid:2500,discount:100,terms:'Thank you for your business.',items:[{name:'CCTV Camera 2MP',unit:'PCS',qty:2,rate:2500},{name:'Installation Service',unit:'JOB',qty:1,rate:1500}]};const html=docHtml(obj,'invoice',t);openModal(`<div class="actions" style="justify-content:space-between;margin-top:0"><div><div class="eyebrow">A4 THEME PREVIEW</div><h2 style="margin:2px 0">${E(label(t))}</h2></div><button class="x" onclick="closeModal()">×</button></div><div class="theme-preview-sheet"><div class="a4-stage">${html}</div></div><div class="actions"><button class="btn" onclick="setDocTheme('${t}');closeModal()">✓ Use This Theme</button><button class="btn secondary" onclick="closeModal()">Close</button></div>`)};
function wireThemes(){document.querySelectorAll('[data-doc-theme]').forEach(b=>{b.onclick=()=>previewDocTheme(b.dataset.docTheme)});document.querySelectorAll('[data-post-theme]').forEach(b=>{b.onclick=()=>{setPendingPostTheme(b.dataset.postTheme)}})}
const oldLoadSettings=window.loadSettings;window.loadSettings=function(){try{oldLoadSettings&&oldLoadSettings()}catch(e){}ensure();document.querySelectorAll('[data-doc-theme]').forEach(x=>x.classList.toggle('active',x.dataset.docTheme===db.settings.docTheme));document.querySelectorAll('[data-post-theme]').forEach(x=>x.classList.toggle('active',x.dataset.postTheme===db.settings.pendingPostTheme));wireThemes()};
window.setDocTheme=function(t){ensure();db.settings.docTheme=t;save();loadSettings();toast('PDF theme set: '+label(t))};
window.setPendingPostTheme=function(t){ensure();db.settings.pendingPostTheme=t;save();loadSettings();toast('Pending post design set: '+t)};
/* Compact single-column billing workspace */
window.renderBilling=function(){const e=document.getElementById('billingEditor');if(!e)return;ensure();const o=iEdit;if(!o){e.innerHTML='<div class="billing-v35-card"><div class="billing-v35-body"><div class="empty">Tap <b>New Invoice</b> to start.</div></div></div>';return}const c=calc(o),pending=Math.max(0,c.total-Number(o.paid||0));const items=o.items||[];e.innerHTML=`<div class="billing-v35">
<div class="billing-v35-card"><div class="billing-v35-head"><div class="eyebrow">SMART BILLING</div><h2>Invoice ${E(o.no)}</h2><p>Mobile app style • works the same on phone and PC</p></div><div class="billing-v35-body">
<div class="v35-section"><h3>👤 Customer & Dates</h3><div class="v35-grid"><div class="full"><label>Customer</label><select onchange="iEdit.customerId=this.value;autoSaveCurrentInvoice()">${customerOptions(o.customerId)}</select></div><div><label>Invoice Date</label><input type="date" value="${E(o.date)}" onchange="iEdit.date=this.value;autoSaveCurrentInvoice()"></div><div><label>Due Date</label><input type="date" value="${E(o.due||'')}" onchange="iEdit.due=this.value;autoSaveCurrentInvoice()"></div></div></div>
<div class="v35-section"><h3>📦 Items & Services <span class="muted small">${items.length} item(s)</span></h3><div class="v35-items">${items.length?items.map((it,n)=>`<div class="v35-item"><div><b>${E(it.name||'Item')}</b><div class="v35-meta">${E(it.unit||'PCS')} • Qty ${Number(it.qty||0)} × ${money(it.rate)} = ${money(Number(it.qty||0)*Number(it.rate||0))}</div></div><div class="v35-item-actions"><button class="btn secondary" onclick="editDocItem('i',${n})">Edit</button><button class="btn danger" onclick="iRemove(${n})">×</button></div></div>`).join(''):'<div class="empty" style="padding:12px">No item added yet.</div>'}</div><button class="v35-add" onclick="addDocItem('invoice')">＋ Add Item / Service</button></div>
<div class="v35-section"><h3>💰 Payment & Pricing</h3><div class="v35-grid three"><div><label>Discount</label><input id="billDiscount" type="number" inputmode="decimal" value="${Number(o.discount||0)}" oninput="iEdit.discount=Number(this.value)||0;updateBillingTotals();autoSaveCurrentInvoice()"></div><div><label>Received / Paid</label><input id="billPaid" type="number" inputmode="decimal" value="${Number(o.paid||0)}" oninput="iEdit.paid=Number(this.value)||0;updateBillingTotals();autoSaveCurrentInvoice()"></div><div><label>Share As</label><select onchange="iEdit.shareAs=this.value;autoSaveCurrentInvoice()"><option value="invoice" ${o.shareAs!=='quotation'?'selected':''}>Invoice</option><option value="quotation" ${o.shareAs==='quotation'?'selected':''}>Quotation</option></select></div></div></div>
<div class="v35-totals"><div class="v35-total"><small>SUBTOTAL</small><b id="billSubtotal">${money(c.sub)}</b></div><div class="v35-total"><small>DISCOUNT</small><b id="billDisc">${money(c.disc)}</b></div><div class="v35-total grand"><small>TOTAL</small><b id="billTotal">${money(c.total)}</b></div><div class="v35-total pending"><small>PENDING</small><b id="billPending">${money(pending)}</b></div></div>
<div class="v35-section"><h3>📝 Terms</h3><textarea oninput="iEdit.terms=this.value;autoSaveCurrentInvoice()">${E(o.terms||'')}</textarea></div>
<div class="v35-sticky"><div class="v35-actions"><button class="btn" onclick="saveBilling()">Save Invoice</button><button class="btn ok" onclick="markFullPaidAndSave()">✓ Full Paid</button><button class="btn accent" onclick="printDoc('invoice')">Print / PDF</button><button class="btn secondary" onclick="viewCurrentBilling()">Preview</button><button class="btn ok" onclick="invoiceWA()">WhatsApp</button><button class="btn secondary" onclick="pendingPost()">Pending Post</button></div><div id="billingAutosaveNote" class="v35-note">✓ Auto-save enabled</div></div>
</div></div></div>`;updateBillingTotals()};
window.updateBillingTotals=(function(orig){return function(){try{orig&&orig()}catch(e){}const s=document.getElementById('billSubtotal'),d=document.getElementById('billDisc'),t=document.getElementById('billTotal'),p=document.getElementById('billPending');if(iEdit){const c=calc(iEdit),pending=Math.max(0,c.total-Number(iEdit.paid||0));if(s)s.textContent=money(c.sub);if(d)d.textContent=money(c.disc);if(t)t.textContent=money(c.total);if(p)p.textContent=money(pending)}}})(window.updateBillingTotals);
/* Reliable saved item picker. No custom item/service button. */
window.showSavedItemPicker=function(type){const ps=(db.products||[]).slice();const rows=ps.length?ps.map(p=>`<button class="sz-pick" onclick="selectSavedItem('${type}','${E(p.id)}')"><span><b>${E(p.name||'Unnamed item')}</b><small>${E(p.unit||'PCS')} • ${money(p.rate||0)}</small></span><strong>＋</strong></button>`).join(''):'<div class="empty">No saved products/services found. Add them from Products first.</div>';openModal(`<div class="sz-item-picker"><div class="actions" style="justify-content:space-between;margin-top:0"><div><div class="eyebrow">ADD TO BILL</div><h2 style="margin:2px 0">Select Item / Service</h2></div><button class="x" onclick="closeModal()">×</button></div><input id="szItemSearch" class="sz-item-search" placeholder="Search item or service…" oninput="filterSzItems(this.value)"><div id="szItemList" class="sz-item-list">${rows}</div><div class="actions"><button class="btn secondary" onclick="closeModal()">Cancel</button></div></div>`);setTimeout(()=>document.getElementById('szItemSearch')?.focus(),80)};
window.filterSzItems=function(q){q=(q||'').toLowerCase();document.querySelectorAll('#szItemList .sz-pick').forEach(x=>x.style.display=(x.innerText||'').toLowerCase().includes(q)?'flex':'none')};
window.selectSavedItem=function(type,id){const o=type==='quote'?qEdit:iEdit,p=(db.products||[]).find(x=>String(x.id)===String(id));if(!o||!p)return toast('Item not found');o.items=o.items||[];o.items.push({id:crypto.randomUUID(),productId:p.id,name:p.name,unit:p.unit||'PCS',qty:1,rate:Number(p.rate)||0});closeModal();if(type==='quote')renderQuoteEditor();else renderBilling();if(type==='invoice')autoSaveCurrentInvoice()};
/* Remove custom item action from any legacy picker if present */
const oldAdd=window.addDocItem;window.addDocItem=function(type){return showSavedItemPicker(type)};
/* Theme document generator wrapper: force selected theme and A4 class */
const baseDoc=window.docHtml;window.docHtml=function(obj,type,themeOverride){ensure();const t=themeOverride||db.settings.docTheme||'modern';if(typeof baseDoc==='function'){let h=baseDoc(obj,type);h=h.replace(/doc-theme-[\w-]+/,'doc-theme-'+E(t));if(!/a4-paper/.test(h))h=h.replace('class="doc ','class="doc a4-paper ');return h}return ''};
/* Browser/Android back: never close app while an in-app page is available. */
let stack=[];let suppress=false;function current(){return document.querySelector('.page.active')?.id||'home'}
const coreOpen=window.openPage;window.openPage=function(id){const c=current();if(id!==c&&!suppress){stack.push(c);if(stack.length>30)stack.shift();history.pushState({sz:id},'',location.href.split('#')[0]+'#'+id)}return coreOpen(id)};
const coreOpenBilling=window.openBilling;window.openBilling=function(){const c=current();if(c!=='billing'&&!suppress){stack.push(c);history.pushState({sz:'billing'},'',location.href.split('#')[0]+'#billing')}return coreOpenBilling()};
function backInApp(){if(document.getElementById('modal')?.classList.contains('show')){closeModal();return true}if(document.getElementById('featureDrawer')?.classList.contains('open')||document.getElementById('menuBackdrop')?.classList.contains('show')){try{closeFeatureMenu()}catch(e){}return true}if(stack.length){const p=stack.pop();suppress=true;coreOpen(p);suppress=false;history.replaceState({sz:p},'',location.href.split('#')[0]+'#'+p);return true}return false}
window.addEventListener('popstate',()=>{if(!backInApp())coreOpen('home')});
/* Advanced actionable local AI */
function aiState(){ensure();const invoices=db.invoices||[],customers=db.customers||[],products=db.products||[];const issues=[],recs=[];const seen={};invoices.forEach(i=>{if(i.id)seen[i.id]=(seen[i.id]||0)+1;if(!i.id)issues.push('Invoice has missing ID: '+(i.no||'Unknown'));const c=calc(i),paid=Number(i.paid||0);if(paid>c.total+.01)issues.push('Paid amount exceeds total: '+(i.no||''));if(!Array.isArray(i.items)||!i.items.length)issues.push('Invoice has no items: '+(i.no||''));if(c.total>0&&paid<c.total&&!i.customerId&&i.status!=='draft')issues.push('Pending invoice has no customer: '+(i.no||''));});Object.keys(seen).forEach(k=>{if(seen[k]>1)issues.push('Duplicate invoice ID: '+k)});customers.forEach(c=>{if(!String(c.name||'').trim())issues.push('Customer without a name')});products.forEach(p=>{if(Number(p.rate)<0)issues.push('Negative product rate: '+(p.name||'item'))});if(!db.settings.name||db.settings.name==='SZ Billing')recs.push({a:'profile',t:'Complete your business profile before sending invoices.'});if(!db.settings.docTheme)recs.push({a:'theme',t:'Choose a professional A4 PDF theme.'});const pending=invoices.filter(i=>Math.max(0,calc(i).total-Number(i.paid||0))>0);if(pending.length)recs.push({a:'pending',t:`Review ${pending.length} pending invoice(s) and prepare payment reminders.`});if(issues.length)recs.push({a:'repair',t:'Run safe data repair to normalize invoice totals and missing fields.'});recs.push({a:'design',t:'Optimize the app and invoice design for a clean professional workflow.'});return {issues:[...new Set(issues)],recs,pending}};
window.aiApplyRecommendation=function(a){try{ensure();if(a==='theme'){db.settings.docTheme='modern';save();loadSettings();toast('A4 PDF theme applied');return}if(a==='design'){db.settings.theme='blue';db.settings.docTheme=db.settings.docTheme||'modern';save();applyTheme();loadSettings();toast('Professional design optimized');return}if(a==='profile'){openPage('settings');toast('Business profile opened');return}if(a==='pending'){if(typeof aiScanAndQueue==='function'){aiScanAndQueue()}else toast('Pending invoices reviewed');return}if(a==='repair'){(db.invoices||[]).forEach(i=>{if(!i.id)i.id=crypto.randomUUID();if(!Array.isArray(i.items))i.items=[];i.items=i.items.map(x=>({...x,qty:Number(x.qty)||0,rate:Number(x.rate)||0,unit:x.unit||'PCS'}));const c=calc(i);i.total=c.total;i.paid=Math.min(Math.max(0,Number(i.paid)||0),c.total);i.pending=Math.max(0,c.total-i.paid)});save();toast('Safe repair applied');return}}catch(e){console.error(e);toast('AI action failed safely')}};
window.aiApplyAllSafe=function(){const r=aiState();[...new Set(r.recs.map(x=>x.a))].forEach(a=>{if(a!=='profile')aiApplyRecommendation(a)});toast('AI safe recommendations implemented')};
window.aiRunCommand=function(){const q=(document.getElementById('aiCommand')?.value||'').toLowerCase().trim();if(!q)return toast('Type a command');if(/fix|repair|bug|correct/.test(q)){aiApplyRecommendation('repair');renderAI?.();return}if(/theme|pdf|invoice design/.test(q)){aiApplyRecommendation('theme');return}if(/design|professional|modern|ui|look/.test(q)){aiApplyRecommendation('design');return}if(/pending|overdue|reminder/.test(q)){aiApplyRecommendation('pending');return}if(/customer|client/.test(q)&&/add|new|create/.test(q)){openPage('customers');openCustomer();return}if(/product|item/.test(q)&&/add|new|create/.test(q)){openPage('products');openProduct();return}if(/invoice|bill/.test(q)&&/new|create|make/.test(q)){newBilling('invoice');return}if(/settings/.test(q)){openPage('settings');return}if(/all|everything|advance|optimize/.test(q)){aiApplyAllSafe();return}renderAI?.();toast('Copilot analyzed your request')};
window.aiAnalyzeV35=function(){const el=document.getElementById('aiResult');if(!el)return;const r=aiState();el.innerHTML=`<div class="card"><div class="ai-grid"><div><b>Business Health</b><div class="ai-score">${r.issues.length?'Needs attention':'Excellent'}</div><div class="muted small">${r.issues.length} issue(s)</div></div><div><b>Suggestions</b><div class="ai-score">${r.recs.length}</div><div class="muted small">actionable improvements</div></div><div><b>Pending</b><div class="ai-score">${r.pending.length}</div><div class="muted small">unpaid invoice(s)</div></div></div></div>`+(r.issues.length?`<div class="card"><b>Detected Issues</b>${r.issues.map(x=>`<div class="item"><span>⚠️ ${E(x)}</span></div>`).join('')}</div>`:'<div class="success-card">✓ No critical billing data issues found.</div>')+`<div class="card"><div class="actions" style="justify-content:space-between"><b>AI Recommendations</b><button class="btn accent" onclick="aiApplyAllSafe()">Apply All Safe</button></div>${r.recs.map(x=>`<div class="item ai-reco"><div><span>💡 ${E(x.t)}</span></div><button class="btn" onclick="aiApplyRecommendation('${x.a}');aiAnalyzeV35()">Apply</button></div>`).join('')}</div>`};
const oldOpenPageV35=window.openPage;window.openPage=function(id){const r=oldOpenPageV35(id);if(id==='ai')setTimeout(aiAnalyzeV35,60);return r};
/* Keep autosave but make it robust and non-blocking */
window.autoSaveCurrentInvoice=function(){if(!iEdit)return;clearTimeout(window.__v35auto);window.__v35auto=setTimeout(()=>{try{const c=calc(iEdit),obj={...iEdit,total:c.total,paid:Number(iEdit.paid||0),pending:Math.max(0,c.total-Number(iEdit.paid||0)),customer:(db.customers.find(x=>x.id===iEdit.customerId)?.name||iEdit.customer||'Draft'),status:iEdit.customerId?'saved':'draft',date:iEdit.date||new Date().toISOString().slice(0,10)};if(obj.id)db.invoices=db.invoices.map(x=>x.id===obj.id?obj:x);else{obj.id=crypto.randomUUID();db.invoices.push(obj)}iEdit={...obj};localStorage.setItem(KEY,JSON.stringify(db));try{cloudQueueSave()}catch(e){}const n=document.getElementById('billingAutosaveNote');if(n)n.textContent='✓ Auto-saved';}catch(e){console.error(e)}},250)};
/* Ensure legacy custom button is hidden if old DOM gets rendered */
function removeCustom(){document.querySelectorAll('button').forEach(b=>{if(/custom item|custom item \/ service/i.test(b.textContent||'')){b.remove()}})}
const obs=new MutationObserver(()=>removeCustom());obs.observe(document.body,{childList:true,subtree:true});
document.addEventListener('DOMContentLoaded',()=>{ensure();wireThemes();setTimeout(()=>{try{loadSettings()}catch(e){};removeCustom()},250)});
})();
