/* V43: payment update reminder + expenses + balance in/out */
(function(){
  function ensureArrays(){
    db.expenses=Array.isArray(db.expenses)?db.expenses:[];
    db.cashflow=Array.isArray(db.cashflow)?db.cashflow:[];
  }
  function addMenuItems(){
    const groups=document.querySelectorAll('#featureDrawer .drawer-group');
    if(!groups.length)return;
    const business=Array.from(groups).find(g=>g.textContent.includes('BUSINESS'));
    if(business && !document.getElementById('drawerExpenses')){
      const b=document.createElement('button');b.className='drawer-item';b.id='drawerExpenses';b.onclick=()=>drawerGo('expenses');b.innerHTML='<span class="drawer-icon">💸</span><span><b>Expenses</b><br><small class="muted">Track business expenses</small></span>';business.appendChild(b);
    }
    const tools=Array.from(groups).find(g=>g.textContent.includes('TOOLS'));
    if(tools && !document.getElementById('drawerCashflow')){
      const b=document.createElement('button');b.className='drawer-item';b.id='drawerCashflow';b.onclick=()=>drawerGo('cashflow');b.innerHTML='<span class="drawer-icon">↕️</span><span><b>Balance In / Out</b><br><small class="muted">Cash received & paid</small></span>';tools.insertBefore(b,tools.firstChild?.nextSibling||null);
    }
  }
  function addPages(){
    const main=document.querySelector('.app>main');if(!main)return;
    if(!document.getElementById('expenses')){
      const s=document.createElement('section');s.id='expenses';s.className='page';s.innerHTML=`<div class="page-head"><div><div class="eyebrow">BUSINESS FINANCE</div><div class="title">Expenses</div><div class="muted small">Track business expenses and see where money is going.</div></div><button class="btn accent" onclick="openExpenseForm()">+ Add Expense</button></div><div class="finance-grid"><div class="card finance-stat"><span class="muted">Total Expenses</span><b id="expenseTotal">Rs. 0</b></div><div class="card finance-stat"><span class="muted">This Month</span><b id="expenseMonth">Rs. 0</b></div></div><div class="card"><div class="section-title">Expense Records</div><div id="expenseList"></div></div>`;main.appendChild(s);
    }
    if(!document.getElementById('cashflow')){
      const s=document.createElement('section');s.id='cashflow';s.className='page';s.innerHTML=`<div class="page-head"><div><div class="eyebrow">CASH MANAGEMENT</div><div class="title">Balance In / Out</div><div class="muted small">Record cash received, payments made and other business movements.</div></div><div class="actions"><button class="btn ok" onclick="openCashflowForm('in')">+ Balance In</button><button class="btn danger" onclick="openCashflowForm('out')">− Balance Out</button></div></div><div class="finance-grid"><div class="card finance-stat"><span class="muted">Balance In</span><b id="cashInTotal">Rs. 0</b></div><div class="card finance-stat"><span class="muted">Balance Out</span><b id="cashOutTotal">Rs. 0</b></div><div class="card finance-stat"><span class="muted">Net Balance</span><b id="cashNetTotal">Rs. 0</b></div></div><div class="card"><div class="section-title">Cash Records</div><div id="cashflowList"></div></div>`;main.appendChild(s);
    }
  }
  function injectStyle(){if(document.getElementById('v43-finance-style'))return;const st=document.createElement('style');st.id='v43-finance-style';st.textContent=`.finance-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:12px}.finance-stat{padding:18px}.finance-stat b{display:block;font-size:23px;margin-top:8px}.finance-row{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center;padding:13px 0;border-bottom:1px solid #e6edf5}.finance-row:last-child{border-bottom:0}.finance-in{color:#087a4d}.finance-out{color:#b42318}@media(max-width:700px){.finance-grid{grid-template-columns:1fr 1fr}.finance-grid .finance-stat:last-child{grid-column:1/-1}}`;document.head.appendChild(st)}
  function renderExpenses(){ensureArrays();const list=document.getElementById('expenseList');if(!list)return;const total=db.expenses.reduce((a,x)=>a+Number(x.amount||0),0);const now=new Date();const month=db.expenses.filter(x=>{const d=new Date(x.date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}).reduce((a,x)=>a+Number(x.amount||0),0);document.getElementById('expenseTotal').textContent=money(total);document.getElementById('expenseMonth').textContent=money(month);list.innerHTML=db.expenses.slice().reverse().map(x=>`<div class="finance-row"><div><b>${esc(x.title)}</b><div class="muted small">${esc(x.category||'General')} • ${esc(x.date||'')}</div>${x.note?`<div class="muted small">${esc(x.note)}</div>`:''}</div><div style="text-align:right"><b class="finance-out">− ${money(x.amount)}</b><button class="btn danger" style="margin-top:6px" onclick="deleteExpense('${x.id}')">Delete</button></div></div>`).join('')||'<div class="empty">No expenses recorded.</div>'}
  function renderCashflow(){ensureArrays();const list=document.getElementById('cashflowList');if(!list)return;const ins=db.cashflow.filter(x=>x.type==='in').reduce((a,x)=>a+Number(x.amount||0),0),outs=db.cashflow.filter(x=>x.type==='out').reduce((a,x)=>a+Number(x.amount||0),0);document.getElementById('cashInTotal').textContent=money(ins);document.getElementById('cashOutTotal').textContent=money(outs);document.getElementById('cashNetTotal').textContent=money(ins-outs);list.innerHTML=db.cashflow.slice().reverse().map(x=>`<div class="finance-row"><div><b>${esc(x.title)}</b><div class="muted small">${esc(x.category||'General')} • ${esc(x.date||'')}</div>${x.note?`<div class="muted small">${esc(x.note)}</div>`:''}</div><div style="text-align:right"><b class="${x.type==='in'?'finance-in':'finance-out'}">${x.type==='in'?'+':'−'} ${money(x.amount)}</b><button class="btn danger" style="margin-top:6px" onclick="deleteCashflow('${x.id}')">Delete</button></div></div>`).join('')||'<div class="empty">No balance records yet.</div>'}
  window.openExpenseForm=function(){openModal(`<h2>Add Expense</h2><label>Expense Name</label><input id="finTitle" placeholder="e.g. Fuel, Internet, Office supplies"><div class="row" style="margin-top:10px"><div><label>Amount</label><input id="finAmount" type="number" inputmode="decimal" step="0.01"></div><div><label>Category</label><select id="finCategory"><option>General</option><option>Fuel / Travel</option><option>Internet / Phone</option><option>Office</option><option>Purchase</option><option>Salary / Labour</option><option>Other</option></select></div></div><label style="margin-top:10px">Date</label><input id="finDate" type="date" value="${new Date().toISOString().slice(0,10)}"><label style="margin-top:10px">Note</label><textarea id="finNote" placeholder="Optional note"></textarea><div class="actions"><button class="btn accent" onclick="saveExpense()">Save Expense</button><button class="btn secondary" onclick="closeModal()">Cancel</button></div>`)};
  window.saveExpense=function(){ensureArrays();const title=document.getElementById('finTitle')?.value.trim(),amount=Number(document.getElementById('finAmount')?.value||0);if(!title)return toast('Expense name required');if(amount<=0)return toast('Enter a valid amount');db.expenses.push({id:crypto.randomUUID(),title,amount,category:document.getElementById('finCategory').value,date:document.getElementById('finDate').value||new Date().toISOString().slice(0,10),note:document.getElementById('finNote').value.trim()});closeModal();save();renderExpenses();toast('Expense added')};
  window.deleteExpense=function(id){if(!confirm('Delete this expense?'))return;db.expenses=db.expenses.filter(x=>x.id!==id);save();renderExpenses();toast('Expense deleted')};
  window.openCashflowForm=function(type){openModal(`<h2>${type==='in'?'Balance In':'Balance Out'}</h2><label>Description</label><input id="finTitle" placeholder="e.g. Customer payment / supplier payment"><div class="row" style="margin-top:10px"><div><label>Amount</label><input id="finAmount" type="number" inputmode="decimal" step="0.01"></div><div><label>Category</label><select id="finCategory"><option>General</option><option>Customer Payment</option><option>Supplier Payment</option><option>Owner / Capital</option><option>Other</option></select></div></div><label style="margin-top:10px">Date</label><input id="finDate" type="date" value="${new Date().toISOString().slice(0,10)}"><label style="margin-top:10px">Note</label><textarea id="finNote" placeholder="Optional note"></textarea><div class="actions"><button class="btn ${type==='in'?'ok':'danger'}" onclick="saveCashflow('${type}')">Save ${type==='in'?'Balance In':'Balance Out'}</button><button class="btn secondary" onclick="closeModal()">Cancel</button></div>`)};
  window.saveCashflow=function(type){ensureArrays();const title=document.getElementById('finTitle')?.value.trim(),amount=Number(document.getElementById('finAmount')?.value||0);if(!title)return toast('Description required');if(amount<=0)return toast('Enter a valid amount');db.cashflow.push({id:crypto.randomUUID(),type,title,amount,category:document.getElementById('finCategory').value,date:document.getElementById('finDate').value||new Date().toISOString().slice(0,10),note:document.getElementById('finNote').value.trim()});closeModal();save();renderCashflow();toast(type==='in'?'Balance In added':'Balance Out added')};
  window.deleteCashflow=function(id){if(!confirm('Delete this balance record?'))return;db.cashflow=db.cashflow.filter(x=>x.id!==id);save();renderCashflow();toast('Balance record deleted')};
  function paymentUpdatePrompt(inv,oldPaid,newPaid){const cu=db.customers.find(x=>x.id===inv.customerId);if(!cu||!cu.wa)return;const pending=Math.max(0,Number(inv.total||0)-Number(newPaid||0));if(newPaid<=oldPaid)return;openModal(`<h2>Payment Update Ready</h2><div class="card" style="margin:10px 0"><b>${esc(cu.name)}</b><div class="muted small">Invoice ${esc(inv.no||'')}</div><div style="margin-top:10px">Total Bill: <b>${money(inv.total)}</b><br>Received: <b>${money(newPaid)}</b><br>Pending: <b>${money(pending)}</b></div></div><p class="muted small">A pending-payment post will show the amount received and the remaining balance.</p><div class="actions"><button class="btn ok" onclick="sendPaymentUpdate('${inv.id}')">💬 Send Update</button><button class="btn secondary" onclick="closeModal()">Later</button></div>`)}
  window.sendPaymentUpdate=function(id){const inv=db.invoices.find(x=>x.id===id);if(!inv)return toast('Invoice not found');iEdit={...inv};closeModal();pendingPostSend(false)};
  const oldSaveInvoice=window.saveInvoice;
  window.saveInvoice=function(){
    if(!iEdit)return toast('Open Invoice first');
    ensureArrays();
    const existing=iEdit.id?db.invoices.find(x=>x.id===iEdit.id):null;
    const oldPaid=existing?Number(existing.paid||0):0;
    const result=oldSaveInvoice.apply(this,arguments);
    const saved=iEdit&&iEdit.id?db.invoices.find(x=>x.id===iEdit.id):null;
    if(saved&&Number(saved.paid||0)>oldPaid){setTimeout(()=>paymentUpdatePrompt(saved,oldPaid,Number(saved.paid||0)),180)}
    return result;
  };
  const oldMark=window.markSavedInvoicePaid;
  window.markSavedInvoicePaid=function(id){const inv=db.invoices.find(x=>x.id===id);const old=inv?Number(inv.paid||0):0;const r=oldMark.apply(this,arguments);const saved=db.invoices.find(x=>x.id===id);if(saved&&Number(saved.paid||0)>old)setTimeout(()=>paymentUpdatePrompt(saved,old,Number(saved.paid||0)),180);return r};
  const oldOpenPage=window.openPage;
  window.openPage=function(id){const r=oldOpenPage.apply(this,arguments);if(id==='expenses')renderExpenses();if(id==='cashflow')renderCashflow();return r};
  document.addEventListener('DOMContentLoaded',()=>{ensureArrays();addPages();addMenuItems();injectStyle();setTimeout(()=>{renderExpenses();renderCashflow();addMenuItems()},150)});
})();
